my:
  #外部文件存储目录(下面有logs存储日志,avatar存储头像,temp文件临时目录,file文件真实目录)
  outFileFolder: D:/netdiskfile
#  outFileFolder: /mnt/mydisk/netdiskfile
  #邮箱验证码的过期时间,单位：分钟
  invalidEmailTime: 10
  #用户的网盘空间,单位:MB
  TotalSpace: 10240
  log:
    #日志级别配置(info或debug)
    level: debug
    #日志目录名称
    path: logs

#自定义的配置
jwt:
  token:
    tokenExpiration: 120 #有效时间min
    tokenSignKey: netdisk123465 #自定义的签名密钥

#  #超级管理员id
#admin.emails=test@qq.com
#  #是否是开发环境
#dev=false
