#发送邮件配置相关
spring:
  mail:
    # 配置邮件服务器的地址 smtp.qq.com
    host: smtp.qq.com
    # 配置邮件服务器的端口（465或587）
    port: 465
    # 配置用户的账号
    username: 1311540039@qq.com
    # 配置用户的密码
    password:
    # 配置默认编码
    default-encoding: UTF-8
    properties:
      mail:
        # 开启 debug，这样方便开发者查看邮件发送日志
        debug: true
        smtp:
          socketFactory:
            # SSL 连接配置
            class: javax.net.ssl.SSLSocketFactory
