#数据库配置
spring:
  datasource:
    url: jdbc:mysql://113.54.235.142:3306/netdisk
    username: netdisk_user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialSize:
      pool-name: HikariCPDatasource
      minimum-idle: 5 #连接池中维持的最小空闲连接数。
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
