log:
  #日志级别配置(info或debug)
  level: debug
  #日志目录
  path: logs


#  #超级管理员id
#admin.emails=test@qq.com
#  #是否是开发环境
#dev=false
#  ##qq登陆相关##
#qq.app.id=12333
#qq.app.key=2222222
#qq.url.authorization=https://graph.qq.com/oauth2.0/authorize?response_type=code&client_id=%s&redirect_uri=%s&state=%s
#qq.url.access.token=https://graph.qq.com/oauth2.0/token?grant_type=authorization_code&client_id=%s&client_secret=%s&code=%s&redirect_uri=%s
#qq.url.openid=https://graph.qq.com/oauth2.0/me?access_token=%S
#qq.url.user.info=https://graph.qq.com/user/get_user_info?access_token=%s&oauth_consumer_key=%s&openid=%s
#qq.url.redirect=http://easypan.wuhancoder.com/qqlogincalback
